name: Build pytcc and run unittests
on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-10.15]
        arch: [x64]

    runs-on: ${{matrix.os}}

    steps:

      - name: Install libc headers
        shell: bash
        run: |
          gcc -xc -E -v -

      - name: Checkout Repository
        uses: actions/checkout@v1.2.0
        with:
          submodules: true

      - name: Build static libtcc and runtime library (libtcc1.a)
        shell: bash
        run: |
          case ${{matrix.os}} in
            "ubuntu-18.04") OS=linux;;
            "windows-2019") OS=win;;
            "macos-10.15")  OS=mac;;
          esac
          case ${{matrix.arch}} in
            x86) ARCHBITS=32;;
            x64) ARCHBITS=64;;
          esac
          case ${OS}${ARCHBITS} in
            win32) ARCHOPTS='-A Win32';;
            win64) ARCHOPTS='-A x64';;
          esac
          OUT_DIR=tinycc-bin/${OS}${ARCHBITS}
          cmake -B $OUT_DIR $ARCHOPTS
          cmake --build $OUT_DIR --config Release

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: ${{matrix.arch}}

      - name: Build Wheel
        run: |
          python -m pip wheel -w wheels .

      - name: Run Unittests
        shell: bash
        run: |
          python -m venv venv
          . venv/*/activate
          pip install -f wheels pytcc pytest
          pytest
